#!/system/xbin/bash

# options: 'noop cfq sio'
SCHED='noop'

insmod /system/lib/modules/sio-iosched.ko

echo $SCHED > /sys/block/mmcblk0/queue/scheduler
echo 0 > /sys/block/mmcblk0/queue/rotational
echo 1 > /sys/block/mmcblk0/queue/iosched/low_latency
echo 1 > /sys/block/mmcblk0/queue/iosched/back_seek_penalty
echo 1000000000 > /sys/block/mmcblk0/queue/iosched/back_seek_max
echo 0 > /sys/block/mmcblk0/queue/iosched/slice_idle
echo 1 > /sys/block/mmcblk0/queue/iosched/fifo_batch
echo 16 > /sys/block/mmcblk0/queue/iosched/quantum
echo 512 > /sys/block/mmcblk0/queue/nr_requests
echo 0 > /sys/block/mmcblk0/queue/iostats

echo $SCHED > /sys/block/mmcblk1/queue/scheduler
echo 0 > /sys/block/mmcblk1/queue/rotational
echo 1 > /sys/block/mmcblk1/queue/iosched/low_latency
echo 1 > /sys/block/mmcblk1/queue/iosched/back_seek_penalty
echo 1000000000 > /sys/block/mmcblk1/queue/iosched/back_seek_max
echo 0 > /sys/block/mmcblk1/queue/iosched/slice_idle
echo 1 > /sys/block/mmcblk1/queue/iosched/fifo_batch
echo 16 > /sys/block/mmcblk1/queue/iosched/quantum
echo 512 > /sys/block/mmcblk1/queue/nr_requests
echo 0 > /sys/block/mmcblk1/queue/iostats
